# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2872f1d5f55c37b5f0988a3edb2cdf37717ee36d30463303b18cd9a4af593708ad4994cb647ed1487627e56a3d341db97ab873b3b22477f0cca4c68525672895

test:
  secret_key_base: d89c156f7c413e5422f72758187b9fc90bcd6f6cf81fae5fe34876f49390379b5e402697bc7c696400514ca30fe294cedb875885a9864ef5b58202c18da81bc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
